lane :test do
  huawei_appgallery(
      client_id: "#{client_id_from_the_developer_console}",
      client_secret: "#{client_secret_from_the_developer_console}",
      app_id: "#{app_id_from_the_developer_console}",
      release_notes: {
        "en-US" => "Bug fixes",
        "de-DE" => "Fehlerbehebungen"
      },
      apk_path: "path/to/app.apk"
    )
end
